
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prdigma
 */
public class Absensi extends javax.swing.JFrame {
    String nol_jam = "";
    String nol_menit = "";
    String nol_detik = "";
    /**
     * Creates new form layout1
     */
    public Absensi() {
        initComponents();
        SetJam();
        setTanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnmasuk = new javax.swing.JButton();
        btnpulang = new javax.swing.JButton();
        btnadmin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        jamlabel = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        kode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HOME");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(230, 10, 420, 50);
        jPanel2.add(icon);
        icon.setBounds(0, -30, 210, 230);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 60));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        jLabel8.setText("Kode Guru");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 0, 210, 50);

        jLabel7.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        jLabel7.setText("Password");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 90, 210, 50);

        btnmasuk.setBackground(new java.awt.Color(255, 255, 255));
        btnmasuk.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnmasuk.setText("Login");
        btnmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmasukActionPerformed(evt);
            }
        });
        jPanel3.add(btnmasuk);
        btnmasuk.setBounds(340, 90, 110, 31);

        btnpulang.setBackground(new java.awt.Color(255, 255, 255));
        btnpulang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnpulang.setText("Exit");
        btnpulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpulangActionPerformed(evt);
            }
        });
        jPanel3.add(btnpulang);
        btnpulang.setBounds(470, 90, 110, 31);

        btnadmin.setBackground(new java.awt.Color(255, 255, 255));
        btnadmin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnadmin.setText("Admin");
        btnadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminActionPerformed(evt);
            }
        });
        jPanel3.add(btnadmin);
        btnadmin.setBounds(510, 140, 70, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Masuk jam : 06:00:00");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 170, 180, 22);

        txtnama.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(txtnama);
        txtnama.setBounds(20, 40, 280, 40);

        txtpass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(txtpass);
        txtpass.setBounds(20, 130, 280, 40);

        jamlabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jamlabel.setForeground(new java.awt.Color(153, 0, 0));
        jamlabel.setText("fs");
        jPanel3.add(jamlabel);
        jamlabel.setBounds(430, 20, 170, 40);

        label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label.setForeground(new java.awt.Color(153, 0, 0));
        label.setText("fd");
        jPanel3.add(label);
        label.setBounds(430, 0, 170, 40);
        jPanel3.add(kode);
        kode.setBounds(340, 150, 0, 0);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, 210));

        setSize(new java.awt.Dimension(607, 295));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnpulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpulangActionPerformed
     
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnpulangActionPerformed

    private void btnmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmasukActionPerformed
        Connection connection;
        PreparedStatement ps;
                       
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost/db_presensi?zeroDateTimeBehavior=convertToNull", "root", "");
            ps = connection.prepareStatement("SELECT `kode_guru`, `password`, `kode_guru` FROM `user` WHERE `kode_guru` = ? AND `password` = ?");
            ps.setString(1, txtnama.getText());
            ps.setString(2, txtpass.getText());
            ResultSet result =ps.executeQuery();
            if(result.next()){
                String a = txtnama.getText();
                new Present(a).setVisible(true);
                this.dispose();
                
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Salah!");
                txtpass.setText("");
                txtnama.requestFocus();
            }
            
            
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(rootPane,"Gagal!");
        }
        
                
        
    }//GEN-LAST:event_btnmasukActionPerformed

    private void btnadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminActionPerformed
        // TODO add your handling code here:
        new adminn().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnadminActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Absensi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadmin;
    private javax.swing.JButton btnmasuk;
    private javax.swing.JButton btnpulang;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jamlabel;
    private javax.swing.JLabel kode;
    private javax.swing.JLabel label;
    private javax.swing.JTextField txtnama;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
    
    public void setTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new
        java.text.SimpleDateFormat("dd-MM-yyyy");
        label.setText("Tanggal : "+kal.format(skrg));
    }

    public void SetJam(){
         ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if (nilai_jam <= 9) {
                    nol_jam = "0";
                }
                if (nilai_menit <=9) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                jamlabel.setText("Jam       : "+jam+ ":" + menit +":"+detik);
            }
        };
    new Timer(60, taskPerformer).start();
     }
     }

                 

                 
