
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mochammad Alauddin
 */
public class data extends javax.swing.JFrame {
    String nol_jam = "";
    String nol_menit = "";
    String nol_detik = "";
    /**
     * Creates new form data
     */
    public data(String a,String c, String d, String e, String f, String g, String h ) {
        

        initComponents();
        txtuser.setText(a);
        txtid.setText(c);
        txtkode.setText(d);
        txtnama2.setText(e);
        txtalamat.setText(f);
        txtnohp.setText(g);
        txtpass.setText(h);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtuser1 = new javax.swing.JLabel();
        txtuser = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtid = new javax.swing.JLabel();
        btnexit = new javax.swing.JButton();
        txtpass = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtkode = new javax.swing.JLabel();
        txtnama2 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JLabel();
        txtnohp = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(655, 475));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Absensi Harian Guru");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(100, 20, 480, 30);

        txtuser1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtuser1.setForeground(new java.awt.Color(255, 255, 255));
        txtuser1.setText("User : ");
        jPanel2.add(txtuser1);
        txtuser1.setBounds(10, 40, 90, 30);

        txtuser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtuser.setForeground(new java.awt.Color(255, 255, 255));
        txtuser.setText("vds");
        jPanel2.add(txtuser);
        txtuser.setBounds(50, 40, 90, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 640, 68);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel10.setText("Nama");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 130, 110, 50);

        jLabel11.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel11.setText("Alamat");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(20, 180, 100, 50);

        jLabel12.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel12.setText("Mapel");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(20, 230, 120, 50);

        btnback.setBackground(new java.awt.Color(204, 204, 255));
        btnback.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel3.add(btnback);
        btnback.setBounds(460, 330, 80, 29);

        jLabel13.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel13.setText("Password");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(20, 280, 120, 50);

        txtid.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jPanel3.add(txtid);
        txtid.setBounds(170, 30, 270, 50);

        btnexit.setBackground(new java.awt.Color(255, 102, 102));
        btnexit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel3.add(btnexit);
        btnexit.setBounds(550, 330, 80, 31);

        txtpass.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jPanel3.add(txtpass);
        txtpass.setBounds(170, 280, 450, 50);

        jLabel18.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel18.setText(":");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(150, 280, 20, 50);

        jLabel19.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel19.setText(":");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(150, 230, 20, 50);

        jLabel20.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel20.setText(":");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(150, 180, 20, 50);

        jLabel21.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel21.setText(":");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(150, 130, 20, 50);

        jLabel22.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel22.setText("Id User");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(20, 30, 130, 50);

        txtkode.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jPanel3.add(txtkode);
        txtkode.setBounds(170, 80, 450, 50);

        txtnama2.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jPanel3.add(txtnama2);
        txtnama2.setBounds(170, 130, 450, 50);

        txtalamat.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jPanel3.add(txtalamat);
        txtalamat.setBounds(170, 180, 450, 50);

        txtnohp.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jPanel3.add(txtnohp);
        txtnohp.setBounds(170, 230, 450, 50);

        jLabel15.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel15.setText("DATA GURU");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(260, 0, 210, 50);

        jLabel23.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel23.setText("Kode Guru");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(20, 80, 130, 50);

        jLabel24.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel24.setText(":");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(150, 80, 20, 50);

        jLabel25.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel25.setText(":");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(150, 30, 20, 50);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 68, 640, 370);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        String a = txtuser.getText();
        new Present(a).setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data(null,null, null, null, null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnexit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtalamat;
    private javax.swing.JLabel txtid;
    private javax.swing.JLabel txtkode;
    private javax.swing.JLabel txtnama2;
    private javax.swing.JLabel txtnohp;
    private javax.swing.JLabel txtpass;
    private javax.swing.JLabel txtuser;
    private javax.swing.JLabel txtuser1;
    // End of variables declaration//GEN-END:variables
  
     }
