
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gerald junha + akbar
 */
public class Edit_data extends javax.swing.JFrame {

    /**
     * Creates new form Konfirmasi
     */
    public Edit_data(String ae) {
        initComponents();
       txtadmin.setText(ae);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtadmin = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        hasil6 = new javax.swing.JLabel();
        hasil1 = new javax.swing.JLabel();
        txtpass = new javax.swing.JTextField();
        hasil2 = new javax.swing.JLabel();
        hasil3 = new javax.swing.JLabel();
        hasil4 = new javax.swing.JLabel();
        hasil5 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtnomer = new javax.swing.JTextField();
        hasil7 = new javax.swing.JLabel();
        hasil8 = new javax.swing.JLabel();
        hasil9 = new javax.swing.JLabel();
        hasil10 = new javax.swing.JLabel();
        hasil11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(199, 22, 22));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tambah data user");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(130, 10, 480, 30);

        txtadmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtadmin.setForeground(new java.awt.Color(255, 255, 255));
        txtadmin.setText("admin");
        jPanel2.add(txtadmin);
        txtadmin.setBounds(10, 30, 140, 15);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 640, 50);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);
        jPanel3.add(icon);
        icon.setBounds(0, 220, 250, 250);

        hasil6.setFont(new java.awt.Font("AlwaysForever", 1, 18)); // NOI18N
        hasil6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hasil6.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(hasil6);
        hasil6.setBounds(250, 180, 150, 40);

        hasil1.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil1.setText("Password ");
        jPanel3.add(hasil1);
        hasil1.setBounds(10, 170, 120, 40);
        jPanel3.add(txtpass);
        txtpass.setBounds(150, 170, 320, 30);

        hasil2.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil2.setText(":");
        jPanel3.add(hasil2);
        hasil2.setBounds(130, 170, 30, 40);

        hasil3.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil3.setText("Nama Guru ");
        jPanel3.add(hasil3);
        hasil3.setBounds(10, 50, 120, 40);

        hasil4.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil4.setText("Alamat ");
        jPanel3.add(hasil4);
        hasil4.setBounds(10, 90, 120, 40);

        hasil5.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil5.setText("Pengajar");
        jPanel3.add(hasil5);
        hasil5.setBounds(10, 130, 120, 40);
        jPanel3.add(txtkode);
        txtkode.setBounds(150, 10, 320, 30);
        jPanel3.add(txtnama);
        txtnama.setBounds(150, 50, 320, 30);
        jPanel3.add(txtalamat);
        txtalamat.setBounds(150, 90, 320, 30);
        jPanel3.add(txtnomer);
        txtnomer.setBounds(150, 130, 320, 30);

        hasil7.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil7.setText("Kode Guru ");
        jPanel3.add(hasil7);
        hasil7.setBounds(10, 10, 120, 40);

        hasil8.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil8.setText(":");
        jPanel3.add(hasil8);
        hasil8.setBounds(130, 10, 30, 40);

        hasil9.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil9.setText(":");
        jPanel3.add(hasil9);
        hasil9.setBounds(130, 50, 30, 40);

        hasil10.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil10.setText(":");
        jPanel3.add(hasil10);
        hasil10.setBounds(130, 90, 30, 40);

        hasil11.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil11.setText(":");
        jPanel3.add(hasil11);
        hasil11.setBounds(130, 130, 30, 40);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(490, 50, 120, 30);

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel3.add(btnsimpan);
        btnsimpan.setBounds(490, 10, 120, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 50, 640, 460);

        setSize(new java.awt.Dimension(650, 302));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ae = txtadmin.getText();
        new table_user(ae).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
               
        if ("".equals(txtkode.getText())  || "".equals(txtnama.getText()) || "".equals(txtalamat.getText())|| "".equals(txtnomer.getText())|| "".equals(txtpass.getText())){
            JOptionPane.showMessageDialog(this, "Harap Lengakapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String SQL = "insert into user (kode_guru,nama_guru,Alamat,pengajar,password)"
                    + "VALUES('"+txtkode.getText()+"','"+txtnama.getText()+"','"+txtalamat.getText()+"','"+txtnomer.getText()+"','"+txtpass.getText()+"')";
            int status;
            try {
                status = KoneksiDB.execute(SQL);
                if (status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil di tambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                String ae = txtadmin.getText();
                new table_user(ae).setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal di tambahkan", "Warning!!!", JOptionPane.INFORMATION_MESSAGE);
            }
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Edit_data.class.getName()).log(Level.SEVERE, null, ex);
            }      
                    
                    
                    
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_data(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel hasil1;
    private javax.swing.JLabel hasil10;
    private javax.swing.JLabel hasil11;
    private javax.swing.JLabel hasil2;
    private javax.swing.JLabel hasil3;
    private javax.swing.JLabel hasil4;
    private javax.swing.JLabel hasil5;
    private javax.swing.JLabel hasil6;
    private javax.swing.JLabel hasil7;
    private javax.swing.JLabel hasil8;
    private javax.swing.JLabel hasil9;
    private javax.swing.JLabel icon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtadmin;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnomer;
    private javax.swing.JTextField txtpass;
    // End of variables declaration//GEN-END:variables
}
