
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prdigma
 */
public class Present extends javax.swing.JFrame {
    String nol_jam = "";
    String nol_menit = "";
    String nol_detik = "";
    int nol, nul;
    /**
     * Creates new form layout1
     */
    public Present(String a) {
        initComponents();
        SetJam();
        setTanggal();
        txtid.setText(a);
        Jam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtid1 = new javax.swing.JLabel();
        txtid = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnmasuk = new javax.swing.JButton();
        btnpulang = new javax.swing.JButton();
        jamlabel = new javax.swing.JLabel();
        btnbiodata = new javax.swing.JButton();
        tanggallabel = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(-30, -30, 10, 10);

        jPanel2.setBackground(new java.awt.Color(204, 0, 51));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Absensi");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(140, 10, 360, 50);

        txtid1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtid1.setForeground(new java.awt.Color(255, 255, 255));
        txtid1.setText("User : ");
        jPanel2.add(txtid1);
        txtid1.setBounds(10, 50, 140, 15);

        txtid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtid.setForeground(new java.awt.Color(255, 255, 255));
        txtid.setText("nfdj");
        jPanel2.add(txtid);
        txtid.setBounds(50, 50, 140, 15);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 440, 70);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        btnmasuk.setBackground(new java.awt.Color(204, 204, 255));
        btnmasuk.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        btnmasuk.setText("Masuk");
        btnmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmasukActionPerformed(evt);
            }
        });
        jPanel3.add(btnmasuk);
        btnmasuk.setBounds(10, 40, 200, 110);

        btnpulang.setBackground(new java.awt.Color(204, 204, 255));
        btnpulang.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        btnpulang.setText("Pulang");
        btnpulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpulangActionPerformed(evt);
            }
        });
        jPanel3.add(btnpulang);
        btnpulang.setBounds(220, 40, 200, 110);

        jamlabel.setBackground(new java.awt.Color(102, 0, 0));
        jamlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jamlabel.setForeground(new java.awt.Color(255, 0, 0));
        jamlabel.setText("njn");
        jPanel3.add(jamlabel);
        jamlabel.setBounds(340, 10, 180, 22);

        btnbiodata.setBackground(new java.awt.Color(153, 153, 153));
        btnbiodata.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnbiodata.setText("Biodata");
        btnbiodata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbiodataActionPerformed(evt);
            }
        });
        jPanel3.add(btnbiodata);
        btnbiodata.setBounds(10, 160, 90, 30);

        tanggallabel.setBackground(new java.awt.Color(102, 0, 0));
        tanggallabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggallabel.setForeground(new java.awt.Color(255, 0, 0));
        tanggallabel.setText("njn");
        jPanel3.add(tanggallabel);
        tanggallabel.setBounds(10, 10, 180, 22);

        btnlogout.setBackground(new java.awt.Color(153, 153, 153));
        btnlogout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel3.add(btnlogout);
        btnlogout.setBounds(330, 160, 90, 30);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        txt.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        txt.setForeground(new java.awt.Color(153, 0, 0));
        txt.setText("   ");
        jPanel4.add(txt);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(160, 160, 170, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Ket :");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(110, 160, 70, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 70, 440, 210);

        setSize(new java.awt.Dimension(445, 304));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnpulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpulangActionPerformed
        // TODO add your handling code here:
        Setpulang();
        String SQL = "SELECT * FROM user where kode_guru='"+txtid.getText()+"'";
        ResultSet rs;
        
        try {
            rs = KoneksiDB.executeQuery(SQL);
            if(rs.next()){
                String id_absen = rs.getString(1);
                String kode_guru = rs.getString(2);
                String nama_guru = rs.getString(3);
                String Alamat = rs.getString(4);
                String pengajar = rs.getString(5);
                String password = rs.getString(6);
                
              String data[] = {id_absen,kode_guru,nama_guru,Alamat,pengajar,password};
              String SQ = "update data SET pulang='"+jamlabel.getText()+"' WHERE kode_guru='"+txtid.getText()+"' AND pulang='"+""+"' AND tanggal='"+tanggallabel.getText()+"'"; 
              int stat;
              stat = KoneksiDB.execute(SQ);
                if (stat == 1){
                JOptionPane.showMessageDialog(this, "Absen pulang berhasil !!!, Anda pulang pada jam : "+jamlabel.getText()+", Dengan Status : "+txt.getText(), "Sukses", JOptionPane.INFORMATION_MESSAGE);
                new Absensi().setVisible(true);
                dispose();
                }else {
                JOptionPane.showMessageDialog(this, "Maaf absen pulang gagal, Dimohon untuk absen masuk terlebih dahulu !!!", "Warning!!!", JOptionPane.INFORMATION_MESSAGE);
                }
            }}catch (SQLException ex){
            Logger.getLogger(table_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnpulangActionPerformed

    private void btnmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmasukActionPerformed
        // TODO add your handling code here:
        Setmasuk();
        String SQL = "SELECT * FROM user where kode_guru='"+txtid.getText()+"'";
        ResultSet rs;
        
        try {
            rs = KoneksiDB.executeQuery(SQL);
            if(rs.next()){
                String id_absen = rs.getString(1);
                String kode_guru = rs.getString(2);
                String nama_guru = rs.getString(3);
                String Alamat = rs.getString(4);
                String pengajar = rs.getString(5);
                String password = rs.getString(6);
                
              String data[] = {id_absen,kode_guru,nama_guru,Alamat,pengajar,password};
              String SQ = "insert into data (kode_guru,nama_guru,Alamat,pengajar,password,tanggal,masuk,pulang,status)"
                    + "VALUES('"+data[1]+"','"+data[2]+"','"+data[3]+"','"+data[4]+"','"+data[5]+"','"+tanggallabel.getText()+"','"+jamlabel.getText()+"','"+""+"','"+txt.getText()+"')";
              int stat;
              stat = KoneksiDB.execute(SQ);
                if (stat == 1){
                JOptionPane.showMessageDialog(this, "Absen masuk berhasil !!!, Anda Masuk pada jam : "+jamlabel.getText()+", Dengan Status : "+txt.getText(), "Sukses", JOptionPane.INFORMATION_MESSAGE);
                new Absensi().setVisible(true);
                dispose();
                }else {
                JOptionPane.showMessageDialog(this, "Dimohon untuk login terlebih dahulu !!!", "Warning!!!", JOptionPane.INFORMATION_MESSAGE);
                }
            }else {
                JOptionPane.showMessageDialog(this, "Data  sangat gagal di tambahkan", "Warning!!!", JOptionPane.INFORMATION_MESSAGE);
                }
        }catch (SQLException ex){
            Logger.getLogger(table_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnmasukActionPerformed

    private void btnbiodataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbiodataActionPerformed
        // TODO add your handling code here:
        Connection connection;
        
            try {
                connection = DriverManager.getConnection("jdbc:mysql://localhost/db_presensi?zeroDateTimeBehavior=convertToNull", "root", "");
                String SQL = "SELECT * FROM user WHERE kode_guru='"+txtid.getText()+"'";
                ResultSet rs = KoneksiDB.executeQuery(SQL);
                rs.next();
                String c = rs.getString(1);
                String d = rs.getString(2);
                String e = rs.getString(3);
                String f = rs.getString(4);
                String g = rs.getString(5);
                String h = rs.getString(6);
                String a = txtid.getText();
                new data(a,c,d,e,f,g,h).setVisible(true);
                this.dispose();
        
            } catch (SQLException ex) {
                Logger.getLogger(Present.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
    }//GEN-LAST:event_btnbiodataActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        new Absensi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Present(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbiodata;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmasuk;
    private javax.swing.JButton btnpulang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jamlabel;
    private javax.swing.JLabel tanggallabel;
    private javax.swing.JLabel txt;
    private javax.swing.JLabel txtid;
    private javax.swing.JLabel txtid1;
    // End of variables declaration//GEN-END:variables
public void SetJam(){
         ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if (nilai_jam <= 9) {
                    nol_jam = "0";
                
                }
                if (nilai_menit <=9) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                jamlabel.setText(jam+ ":" + menit +":"+detik);
                
            }
        };
    new Timer(60, taskPerformer).start();  
     }
public void setTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new
        java.text.SimpleDateFormat("dd-MM-yyyy");
        tanggallabel.setText(kal.format(skrg));
    }

public void Jam(){
         ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if (nilai_jam > 6 ) {
                    txt.setText("Terlambat");
                }else{
                    txt.setText("Tepat");
                }
                
            }
        };
}
        public void Setmasuk(){
            Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if (nilai_jam <= 9) {
                    nol_jam = "0";
                    nul = 0;
                }
                nol = nul + (nilai_jam);
                if(nol<6){
                    txt.setText("Tepat");
                }else{
                    txt.setText("Terlambat");
                }
        }
        public void Setpulang(){
            Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if (nilai_jam <= 9) {
                    nol_jam = "0";
                    nul = 0;
                }
                nol = nul + (nilai_jam);
                if(nol<16){
                    txt.setText("Terlalu Cepat");
                }else{
                    txt.setText("Tepat");
                }
        }
}

