
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gerald junha
 */
public class table_admin2 extends javax.swing.JFrame {
    String nol_jam = "";
    String nol_menit = "";
    String nol_detik = "";
    /**
     * Creates new form about
     */
    public table_admin2(String ae) {
        initComponents();
        SetJam();
        setTanggal();
        txtadmin.setText(ae);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtadmin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpresensi = new javax.swing.JTable();
        btncari = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnexit = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        tanggallabel = new javax.swing.JLabel();
        jamlabel = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        txtadmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtadmin.setForeground(new java.awt.Color(255, 255, 255));
        txtadmin.setText("admin");
        getContentPane().add(txtadmin);
        txtadmin.setBounds(10, 40, 140, 15);

        jPanel2.setBackground(new java.awt.Color(199, 22, 22));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Admin");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(160, 20, 460, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 560, 60);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        tabelpresensi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id_admin", "username", "password"
            }
        ));
        jScrollPane1.setViewportView(tabelpresensi);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 420, 310);

        btncari.setBackground(new java.awt.Color(153, 153, 153));
        btncari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        jPanel3.add(btncari);
        btncari.setBounds(450, 10, 90, 30);

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Add Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(450, 50, 90, 30);

        btnedit.setBackground(new java.awt.Color(153, 153, 153));
        btnedit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel3.add(btnedit);
        btnedit.setBounds(450, 90, 90, 30);

        btndelete.setBackground(new java.awt.Color(153, 153, 153));
        btndelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btndelete);
        btndelete.setBounds(450, 130, 90, 30);

        btnrefresh.setBackground(new java.awt.Color(153, 153, 153));
        btnrefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        jPanel3.add(btnrefresh);
        btnrefresh.setBounds(450, 170, 90, 30);

        jLabel2.setText("-");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(180, 10, 10, 14);

        btnexit.setBackground(new java.awt.Color(255, 102, 102));
        btnexit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel3.add(btnexit);
        btnexit.setBounds(450, 330, 90, 30);

        btnprint.setBackground(new java.awt.Color(153, 153, 153));
        btnprint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnprint.setText("Print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        jPanel3.add(btnprint);
        btnprint.setBounds(450, 210, 90, 30);

        btnhome.setBackground(new java.awt.Color(204, 255, 255));
        btnhome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnhome.setText("Home");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        jPanel3.add(btnhome);
        btnhome.setBounds(450, 250, 90, 30);

        tanggallabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        tanggallabel.setForeground(new java.awt.Color(153, 0, 0));
        tanggallabel.setText("jam");
        jPanel3.add(tanggallabel);
        tanggallabel.setBounds(20, -10, 210, 50);

        jamlabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jamlabel.setForeground(new java.awt.Color(153, 0, 0));
        jamlabel.setText("jam");
        jPanel3.add(jamlabel);
        jamlabel.setBounds(20, 10, 210, 50);

        btnback.setBackground(new java.awt.Color(255, 255, 153));
        btnback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnback.setText("Menu");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel3.add(btnback);
        btnback.setBounds(450, 290, 90, 30);
        jPanel3.add(txtcari);
        txtcari.setBounds(310, 10, 120, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 60, 560, 450);

        setSize(new java.awt.Dimension(574, 470));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        Data();
    }//GEN-LAST:event_btncariActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        int baris = tabelpresensi.getSelectedRow();
        if(baris != -1){
            
            String a = tabelpresensi.getValueAt(baris, 0).toString();
            String b = tabelpresensi.getValueAt(baris, 1).toString();
            String c = tabelpresensi.getValueAt(baris, 2).toString();
            String ae = txtadmin.getText();
            new update_admin(a,b,c,ae).setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int baris = tabelpresensi.getSelectedRow();
        if (baris != -1){
            String id = tabelpresensi.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM admin WHERE id_admin='"+id+"'";
            int status;
            try {
                status = KoneksiDB.execute(SQL);
                if (status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
                selectData();
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(table_admin.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Restoran KU Daftar Harga");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}       ");
        try{
            tabelpresensi.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btnprintActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // TODO add your handling code here:
        new Absensi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnhomeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String ae = txtadmin.getText();
        new add_admin(ae).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        String ae = txtadmin.getText();
        new pilih(ae).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new table_admin2(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jamlabel;
    private javax.swing.JTable tabelpresensi;
    private javax.swing.JLabel tanggallabel;
    private javax.swing.JLabel txtadmin;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
    private void selectData(){
         String kolom[] = {"id_admin","username", "password"};
        DefaultTableModel dtm = new DefaultTableModel (null, kolom);
        String SQL = "SELECT * FROM admin";
        ResultSet rs;
        try {
            rs = KoneksiDB.executeQuery(SQL);
            while(rs.next()){
                String id_admin = rs.getString(1);
                String username = rs.getString(2);
                String password = rs.getString(3);         
              
                String data[] = {id_admin,username,password};
                dtm.addRow(data);
            }
            tabelpresensi.setModel(dtm);
            
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(table_admin2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     }
    
    private void Data(){
        String kolom[] = {"id_admin","username", "password"};
        String dat = txtcari.getText();
        DefaultTableModel dtm = new DefaultTableModel (null, kolom);
        String SQL = "SELECT * FROM admin where id_admin='"+dat+"' OR username='"+dat+"' OR password='"+dat+"'";
        ResultSet rs;
        try {
            rs = KoneksiDB.executeQuery(SQL);
            while(rs.next()){
                String id_admin = rs.getString(1);
                String username = rs.getString(2);
                String password = rs.getString(3);         
              
                String data[] = {id_admin,username,password};
                dtm.addRow(data);
            }
            tabelpresensi.setModel(dtm);
            
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(table_admin2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     }
    
    public void setTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new
        java.text.SimpleDateFormat("dd-MM-yyyy");
        tanggallabel.setText("Tanggal : "+kal.format(skrg));
    }
    public void SetJam(){
         ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if (nilai_jam <= 9) {
                    nol_jam = "0";
                }
                if (nilai_menit <=9) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                jamlabel.setText("Jam       : "+jam+ ":" + menit +":"+detik);
            }
        };
    new Timer(60, taskPerformer).start();
     }
    
     }

