
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gerald junha + akbar
 */
public class update_admin extends javax.swing.JFrame {

    /**
     * Creates new form Konfirmasi
     */
    public update_admin(String a,String b,String c, String ae) {
        initComponents();
       
        txtid.setText(a);
       txtnama.setText(b);
       txtpass.setText(c);
       txtadmin.setText(ae);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtadmin = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        hasil6 = new javax.swing.JLabel();
        hasil3 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtpass = new javax.swing.JTextField();
        txtid = new javax.swing.JLabel();
        hasil8 = new javax.swing.JLabel();
        hasil9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        hasil12 = new javax.swing.JLabel();
        hasil13 = new javax.swing.JLabel();
        hasil14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(199, 22, 22));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Edit Data user");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(160, 10, 480, 30);

        txtadmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtadmin.setForeground(new java.awt.Color(255, 255, 255));
        txtadmin.setText("admin");
        jPanel2.add(txtadmin);
        txtadmin.setBounds(10, 30, 140, 15);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 640, 50);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        hasil6.setFont(new java.awt.Font("AlwaysForever", 1, 18)); // NOI18N
        hasil6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hasil6.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(hasil6);
        hasil6.setBounds(250, 180, 150, 40);

        hasil3.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil3.setText("Password");
        jPanel3.add(hasil3);
        hasil3.setBounds(10, 80, 120, 40);
        jPanel3.add(txtnama);
        txtnama.setBounds(150, 40, 320, 30);
        jPanel3.add(txtpass);
        txtpass.setBounds(150, 80, 320, 30);

        txtid.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jPanel3.add(txtid);
        txtid.setBounds(150, 0, 120, 40);

        hasil8.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil8.setText(":");
        jPanel3.add(hasil8);
        hasil8.setBounds(130, 0, 30, 40);

        hasil9.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil9.setText(":");
        jPanel3.add(hasil9);
        hasil9.setBounds(130, 80, 30, 40);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(490, 80, 120, 30);

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel3.add(btnsimpan);
        btnsimpan.setBounds(490, 40, 120, 30);

        hasil12.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil12.setText("Username");
        jPanel3.add(hasil12);
        hasil12.setBounds(10, 40, 120, 40);

        hasil13.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil13.setText(":");
        jPanel3.add(hasil13);
        hasil13.setBounds(130, 40, 30, 40);

        hasil14.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil14.setText("ID Admin");
        jPanel3.add(hasil14);
        hasil14.setBounds(10, 0, 120, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 50, 640, 460);

        setSize(new java.awt.Dimension(650, 217));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ae = txtadmin.getText();
        new table_admin2(ae).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
               
        if ("".equals(txtnama.getText())  || "".equals(txtpass.getText())){
            JOptionPane.showMessageDialog(this, "Harap Lengakapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String SQL = "update admin SET id_admin='"+txtid.getText()+"',username='"+txtnama.getText()+"',password='"+txtpass.getText()+"' WHERE id_admin='"+txtid.getText()+"'";
            int status;
            try {
                status = KoneksiDB.execute(SQL);
                if (status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil di tambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                String ae = txtadmin.getText();
                new table_admin2(ae).setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal di tambahkan", "Warning!!!", JOptionPane.INFORMATION_MESSAGE);
            }
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(update_user.class.getName()).log(Level.SEVERE, null, ex);
            }      
                    
                    
                    
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_admin(null, null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel hasil12;
    private javax.swing.JLabel hasil13;
    private javax.swing.JLabel hasil14;
    private javax.swing.JLabel hasil3;
    private javax.swing.JLabel hasil6;
    private javax.swing.JLabel hasil8;
    private javax.swing.JLabel hasil9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtadmin;
    private javax.swing.JLabel txtid;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtpass;
    // End of variables declaration//GEN-END:variables
}
