
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gerald junha + akbar
 */
public class update_data_presensi1 extends javax.swing.JFrame {

    /**
     * Creates new form Konfirmasi
     */
    public update_data_presensi1(String a,String b,String c,String d,String e,String f,String g,String h,String i,String j, String ae) {
        initComponents();
        txtadmin.setText(ae);
        txtid.setText(a);
       txtkode.setText(b);
       txtnama.setText(c);
       txtalamat.setText(d);
       txtnomer.setText(e);
       txtpass.setText(f);
       txttanggal.setText(g);
       txtmasuk.setText(h);
       txtpulang.setText(i);
       txtstatus.setText(j);
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtadmin = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        hasil6 = new javax.swing.JLabel();
        hasil1 = new javax.swing.JLabel();
        txtpass = new javax.swing.JTextField();
        hasil2 = new javax.swing.JLabel();
        hasil3 = new javax.swing.JLabel();
        hasil4 = new javax.swing.JLabel();
        hasil5 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtnomer = new javax.swing.JTextField();
        hasil7 = new javax.swing.JLabel();
        txtid = new javax.swing.JLabel();
        hasil9 = new javax.swing.JLabel();
        hasil10 = new javax.swing.JLabel();
        hasil11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        txtstatus = new javax.swing.JTextField();
        hasil12 = new javax.swing.JLabel();
        hasil13 = new javax.swing.JLabel();
        hasil14 = new javax.swing.JLabel();
        hasil15 = new javax.swing.JLabel();
        hasil16 = new javax.swing.JLabel();
        hasil17 = new javax.swing.JLabel();
        hasil18 = new javax.swing.JLabel();
        hasil19 = new javax.swing.JLabel();
        txtmasuk = new javax.swing.JTextField();
        txtpulang = new javax.swing.JTextField();
        hasil20 = new javax.swing.JLabel();
        hasil21 = new javax.swing.JLabel();
        hasil22 = new javax.swing.JLabel();
        txttanggal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(199, 22, 22));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Edit data Presensi");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(130, 10, 480, 30);

        txtadmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtadmin.setForeground(new java.awt.Color(255, 255, 255));
        txtadmin.setText("admin");
        jPanel2.add(txtadmin);
        txtadmin.setBounds(10, 30, 140, 15);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 640, 50);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        hasil6.setFont(new java.awt.Font("AlwaysForever", 1, 18)); // NOI18N
        hasil6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hasil6.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(hasil6);
        hasil6.setBounds(250, 180, 150, 40);

        hasil1.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil1.setText("Status");
        jPanel3.add(hasil1);
        hasil1.setBounds(20, 360, 120, 40);
        jPanel3.add(txtpass);
        txtpass.setBounds(160, 200, 320, 30);

        hasil2.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil2.setText(":");
        jPanel3.add(hasil2);
        hasil2.setBounds(140, 360, 30, 40);

        hasil3.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil3.setText("Nama Guru ");
        jPanel3.add(hasil3);
        hasil3.setBounds(20, 80, 120, 40);

        hasil4.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil4.setText("Alamat ");
        jPanel3.add(hasil4);
        hasil4.setBounds(20, 120, 120, 40);

        hasil5.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil5.setText("Mapel");
        jPanel3.add(hasil5);
        hasil5.setBounds(20, 160, 120, 40);
        jPanel3.add(txtkode);
        txtkode.setBounds(160, 40, 320, 30);
        jPanel3.add(txtnama);
        txtnama.setBounds(160, 80, 320, 30);
        jPanel3.add(txtalamat);
        txtalamat.setBounds(160, 120, 320, 30);
        jPanel3.add(txtnomer);
        txtnomer.setBounds(160, 160, 320, 30);

        hasil7.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil7.setText("ID Absen");
        jPanel3.add(hasil7);
        hasil7.setBounds(20, 0, 120, 40);

        txtid.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jPanel3.add(txtid);
        txtid.setBounds(160, 0, 30, 40);

        hasil9.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil9.setText(":");
        jPanel3.add(hasil9);
        hasil9.setBounds(140, 80, 30, 40);

        hasil10.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil10.setText(":");
        jPanel3.add(hasil10);
        hasil10.setBounds(140, 120, 30, 40);

        hasil11.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil11.setText(":");
        jPanel3.add(hasil11);
        hasil11.setBounds(140, 160, 30, 40);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(500, 80, 120, 30);

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel3.add(btnsimpan);
        btnsimpan.setBounds(500, 40, 120, 30);
        jPanel3.add(txtstatus);
        txtstatus.setBounds(160, 360, 320, 30);

        hasil12.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil12.setText("Password ");
        jPanel3.add(hasil12);
        hasil12.setBounds(20, 200, 120, 40);

        hasil13.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil13.setText("Tanggal");
        jPanel3.add(hasil13);
        hasil13.setBounds(20, 240, 120, 40);

        hasil14.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil14.setText(":");
        jPanel3.add(hasil14);
        hasil14.setBounds(140, 200, 30, 40);

        hasil15.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil15.setText(":");
        jPanel3.add(hasil15);
        hasil15.setBounds(140, 240, 30, 40);

        hasil16.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil16.setText("Masuk");
        jPanel3.add(hasil16);
        hasil16.setBounds(20, 280, 120, 40);

        hasil17.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil17.setText(":");
        jPanel3.add(hasil17);
        hasil17.setBounds(140, 280, 30, 40);

        hasil18.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil18.setText("Pulang");
        jPanel3.add(hasil18);
        hasil18.setBounds(20, 320, 120, 40);

        hasil19.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil19.setText(":");
        jPanel3.add(hasil19);
        hasil19.setBounds(140, 320, 30, 40);
        jPanel3.add(txtmasuk);
        txtmasuk.setBounds(160, 280, 320, 30);
        jPanel3.add(txtpulang);
        txtpulang.setBounds(160, 320, 320, 30);

        hasil20.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil20.setText("Kode Guru ");
        jPanel3.add(hasil20);
        hasil20.setBounds(20, 40, 120, 40);

        hasil21.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil21.setText(":");
        jPanel3.add(hasil21);
        hasil21.setBounds(140, 40, 30, 40);

        hasil22.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        hasil22.setText(":");
        jPanel3.add(hasil22);
        hasil22.setBounds(140, 0, 30, 40);
        jPanel3.add(txttanggal);
        txttanggal.setBounds(160, 240, 320, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 50, 640, 460);

        setSize(new java.awt.Dimension(650, 492));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ae = txtadmin.getText();
        new table_admin(ae).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        if ("".equals(txtstatus.getText())  ||"".equals(txtpulang.getText())  ||"".equals(txttanggal.getText())  ||"".equals(txtmasuk.getText())  ||"".equals(txtkode.getText())  || "".equals(txtnama.getText()) || "".equals(txtalamat.getText())|| "".equals(txtnomer.getText())|| "".equals(txtpass.getText())){
            JOptionPane.showMessageDialog(this, "Harap Lengakapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String SQL = "update data SET id_absen='"+txtid.getText()+"',kode_guru='"+txtkode.getText()+"',nama_guru='"+txtnama.getText()+"',Alamat='"+txtalamat.getText()+"',pengajar='"+txtnomer.getText()+"',password='"+txtpass.getText()+"',tanggal='"+txttanggal.getText()+"',masuk='"+txtmasuk.getText()+"',pulang='"+txtpulang.getText()+"',status='"+txtstatus.getText()+"' WHERE id_absen='"+txtid.getText()+"'";
            int status;
            try {
                status = KoneksiDB.execute(SQL);
                if (status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil di tambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                String ae = txtadmin.getText();
                new table_admin(ae).setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal di tambahkan", "Warning!!!", JOptionPane.INFORMATION_MESSAGE);
            }
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Edit_data.class.getName()).log(Level.SEVERE, null, ex);
            }      
                    
                    
                    
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_data_presensi1(null,null,null,null,null,null,null,null,null,null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel hasil1;
    private javax.swing.JLabel hasil10;
    private javax.swing.JLabel hasil11;
    private javax.swing.JLabel hasil12;
    private javax.swing.JLabel hasil13;
    private javax.swing.JLabel hasil14;
    private javax.swing.JLabel hasil15;
    private javax.swing.JLabel hasil16;
    private javax.swing.JLabel hasil17;
    private javax.swing.JLabel hasil18;
    private javax.swing.JLabel hasil19;
    private javax.swing.JLabel hasil2;
    private javax.swing.JLabel hasil20;
    private javax.swing.JLabel hasil21;
    private javax.swing.JLabel hasil22;
    private javax.swing.JLabel hasil3;
    private javax.swing.JLabel hasil4;
    private javax.swing.JLabel hasil5;
    private javax.swing.JLabel hasil6;
    private javax.swing.JLabel hasil7;
    private javax.swing.JLabel hasil9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtadmin;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JLabel txtid;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtmasuk;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnomer;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtpulang;
    private javax.swing.JTextField txtstatus;
    private javax.swing.JTextField txttanggal;
    // End of variables declaration//GEN-END:variables
}
